MVCBoostrapAlerts/Models/Alert.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCBoostrapAlerts.Models
{
    public class Alert
    {
        public const string TempDataKey = "TempDataAlerts";
        //public const string TempDataKeyAutoDisappear = "AutoDisappear";
        public string AlertStyle { get; set; }
        public string Message { get; set; }
        public bool Dismissable { get; set; }
        public bool AutoDisappear { get; set; }
    }//end class

    public static class AlertStyles
    {
        public const string Success = "success";
        public const string Information = "info";
        public const string Warning = "warning";
        public const string Danger = "danger";
    }//end class
}//end namespace

MVCBoostrapAlerts/Controllers/AlertsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCBoostrapAlerts.Controllers
{
    public class AlertsController : BaseController
    {
        // GET: Alerts
        public ActionResult Index()
        {
            //Auto Disappear-Click to close
            Success("Success-Auto Disappear-Click to close", true, true);
            Information("Information-Auto Disappear-Click to close", true, true);
            Warning("Warning-Auto Disappear-Click to close", true, true);
            Danger("Danger-Auto Disappear-Click to close", true, true);

            //Auto Disappear-Can not Close
            Success("Success-Auto Disappear-Can not Close", true,false);
            Information("Information-Auto Disappear-Can not Close", true,false);
            Warning("Warning-Auto Disappear-Can not Close", true,false);
            Danger("Danger-Auto Disappear-Can not Close", true,false);


            //Not Disappear-Click to close
            Success("Success-Not Disappear-Click to close", false,true);
            Information("Information-Not Disappear-Click to close", false, true);
            Warning("Warning-Not Disappear-Click to close", false, true);
            Danger("Danger-Not Disappear-Click to close", false, true);

            return View();
        }
    }//end class
}//end namespace

MVCBoostrapAlerts/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Security.Principal;
using System.Web.Routing;
using MVCBoostrapAlerts.Models;
namespace MVCBoostrapAlerts.Controllers
{
    public class BaseController : Controller
    {
        readonly log4net.ILog Logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        
        public BaseController()
        {
           
          
        }

        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
           
            //if (!User.Identity.IsAuthenticated)
            //{
            //    Logger.Info("Not Authenticated " + requestContext.HttpContext.Request.RawUrl);
            //    HttpContext.Response.Redirect("~/Account/Login", true);
            //    return;
            //}
            //
           
        }

        public void Success(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Success, message, dismissable);
        }

        public void Success(string message, bool autoDisappear, bool dismissable = false)
        {
            AddAlert(AlertStyles.Success, autoDisappear, message, dismissable);
        }

        public void Information(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Information, message, dismissable);
        }

        public void Information(string message, bool autoDisappear, bool dismissable = false)
        {
            AddAlert(AlertStyles.Information, autoDisappear, message, dismissable);
        }

        public void Warning(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Warning, message, dismissable);
        }

        public void Warning(string message, bool autoDisappear, bool dismissable = false)
        {
            AddAlert(AlertStyles.Warning, autoDisappear, message, dismissable);
        }

        public void Danger(string message, bool dismissable = false)
        {
            AddAlert(AlertStyles.Danger, message, dismissable);
        }

        public void Danger(string message, bool autoDisappear, bool dismissable = false)
        {
            AddAlert(AlertStyles.Danger, autoDisappear, message, dismissable);
        }

        private void AddAlert(string alertStyle, string message, bool dismissable)
        {
            var alerts = TempData.ContainsKey(Alert.TempDataKey)
                ? (List<Alert>)TempData[Alert.TempDataKey]
                : new List<Alert>();

            alerts.Add(new Alert
            {
                AlertStyle = alertStyle,
                Message = message,
                Dismissable = dismissable,
                AutoDisappear=false
            });

            TempData[Alert.TempDataKey] = alerts;
           
        }

        private void AddAlert(string alertStyle, bool autoDisappear, string message, bool dismissable)
        {
            var alerts = TempData.ContainsKey(Alert.TempDataKey)
                ? (List<Alert>)TempData[Alert.TempDataKey]
                : new List<Alert>();

            alerts.Add(new Alert
            {
                AlertStyle = alertStyle,
                Message = message,
                Dismissable = dismissable,
                AutoDisappear = autoDisappear
            });

            TempData[Alert.TempDataKey] = alerts;

        }
    
    }//end class
}//end namespace

//Success(string.Format("<b>{0}</b> was successfully added to the database.", person.FirstName), true);
//Danger("Looks like something went wrong. Please check your form.");

MVCBoostrapAlerts/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCBoostrapAlerts.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVCBoostrapAlerts/Views/Alerts/Index.cshtml
@{
    ViewBag.Title = "MVC Bootstrap Alerts";
}

<h2>Alerts</h2>

<input id="btnAlerts" type="button" value="JavaScript Alerts" class="btn btn-primary" />


@section Scripts {
    <script type="text/javascript">

        $(function () {

            $("#btnAlerts").on("click", function () {
                showBoostrapAlert("From Javascript - Success ", "success", true, false, false);
                showBoostrapAlert("From Javascript - Danger ", "danger", true, false, false);
                showBoostrapAlert("From Javascript - Info ", "info", true, false, false);
                showBoostrapAlert("From Javascript - Warning ", "warning", true, false, false);
            });

            //Show Alert on top
            function showBoostrapAlert(message, style, dismissable, empty, autoclose) {

                if (empty)
                    $("#AlertPartial").empty();

                var html = "";
                var dismissableClass = dismissable ? "alert-dismissable" : null;
                var autoDisappearClass = autoclose ? "alert-disappear" : null;
                html = "<div class='alert alert-" + style + " " + dismissableClass + " " + autoDisappearClass + "' >";


         
                if (dismissable) {
                    html = html + "<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">&times;</button>";

        
                }
                html = html + message + "</div>";
                $("#AlertPartial").append(html);
                $("#AlertPartial").show();

          
                $(".alert-disappear").delay(8000).fadeOut(300);

            };
        });
    </script>
}

MVCBoostrapAlerts/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCBoostrapAlerts/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCBoostrapAlerts/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MVCBoostrapAlerts/Views/Shared/_Alerts.cshtml
@using MVCBoostrapAlerts.Models
@{
    var alerts = TempData.ContainsKey(Alert.TempDataKey)
                ? (List<Alert>)TempData[Alert.TempDataKey]
                : new List<Alert>();
                
    if(alerts.Any())
    {
        <hr/>;
    }
    <div id="AlertPartial" class="AlertPartial">

        @foreach (var alert in alerts)
        {
        var dismissableClass = alert.Dismissable ? "alert-dismissable" : null;
        var autoDisappearClass = alert.AutoDisappear ? "alert-disappear" : null;
        <div class="alert alert-@alert.AlertStyle @dismissableClass @autoDisappearClass">
            @if (alert.Dismissable)
            {
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>

            }
            @Html.Raw(alert.Message)
        </div>;
        }
    </div>
}

<script type="text/javascript">
    $(function () {

        $(".alert-disappear").delay(8000).fadeOut(300);
    });

    

</script>

MVCBoostrapAlerts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Harris Yer Boostrap Alerts Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Boostrap Alerts", "Index", "Alerts", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Alerts", "Index", "Alerts")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderBody()
        @{Html.RenderPartial("_Alerts", new { });}
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Harris Yer Boostrap Alerts Application</p>
        </footer>
    </div>

   
    @RenderSection("scripts", required: false)
</body>
</html>